apiVersion: v1
kind: Service
metadata:
  name: mongo-replica-set
  namespace: development
  labels:
    app: mongo-rs
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo-port
  selector:
    app: mongod
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-rs
  namespace: development
spec:
  serviceName: "mongo-rs"
  replicas: 3
  selector:
    matchLabels:
      app: mongod
  template:
    metadata:
      labels:
        app: mongod
        role: mongo
        environment: test
    spec:
      containers:
      - name: mongod
        image: activemauney/mongod:0.01
        command:
        - mongod
        - "--dbpath"
        - "/var/lib/mongodb/"
        - "--bind_ip"
        - "0.0.0.0"
        - "--port"
        - "27017"
        - "--replSet"
        - rs0
        - "--smallfiles"
        - "--noprealloc"
        ports:
        - containerPort: 27017
          name: mongo-port
        volumeMounts:
        - name: mongo-rs-log
          mountPath: /var/log/mongodb/
        - name: mongo-rs-data
          mountPath: /var/lib/mongodb/
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: "role=mongo,environment=test"
        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: mongo-rs
      volumes:
      - name: mongo-rs-log
        hostPath:
          path: /mnt/lv_db_data/mongo-rs/log/
      - name: mongo-rs-data
        hostPath:
          path: /mnt/lv_db_data/mongo-rs/data/
