from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('existing_investigations', views.existing_investigations, name='existing_investigations'),
    path('new_investigation', views.new_investigation, name='new_investigation'),
    path('monitor_cdlog_extraction', views.monitor_cdlog_extraction, name='monitor_cdlog_extraction'),
    path('dump_cdlog_to_database', views.dump_cdlog_to_database, name='dump_cdlog_to_database'),
    path('api_monitor_dump_cdlog_to_database', views.api_monitor_dump_cdlog_to_database, name='api_monitor_dump_cdlog_to_database'),
    path('api_dump_cdlog_to_database', views.api_dump_cdlog_to_database, name='api_dump_cdlog_to_database'),
    path('batch_cdlog_load', views.batch_cdlog_load, name='batch_cdlog_load'),
    path('load_from_log_server', views.load_from_log_server, name='load_from_log_server'),
    path('purge_log_data', views.purge_log_data, name='purge_log_data'),
    path('view_cdlog_load_state', views.view_cdlog_load_state, name='view_cdlog_load_state'),
    path('cdlog_analysis_home', views.cdlog_analysis_home, name='cdlog_analysis_home'),
    path('initiator_report', views.initiator_report, name='initiator_report'),
    path('raw_desc_table', views.raw_desc_table, name='raw_desc_table'),
    path('desc_table', views.desc_table, name='desc_table'),
    path('raw_execute_group_by', views.raw_execute_group_by, name='raw_execute_group_by'),
    path('api_event_code', views.api_event_code, name='api_event_code'),
    path('api_cluster_director_port', views.api_cluster_director_port, name='api_cluster_director_port'),
    path('api_cluster_storage_view', views.api_cluster_storage_view, name='api_cluster_storage_view'),
    path('api_cluster_storage_view_initiator', views.api_cluster_storage_view_initiator, name='api_cluster_storage_view_initiator'),
    path('api_cluster_storage_view_initiator_target_login', views.api_cluster_storage_view_initiator_target_login, name='api_cluster_storage_view_initiator_target_login'),
    path('api_cluster_engine_director', views.api_cluster_engine_director, name='api_cluster_engine_director'),
    path('api_cluster_array_connectivity', views.api_cluster_array_connectivity, name='api_cluster_array_connectivity'),
    path('api_cluster_array', views.api_cluster_array, name='api_cluster_array'),
    path('api_cluster_array_target', views.api_cluster_array_target, name='api_cluster_array_target'),
    path('api_sys_perf_log', views.api_sys_perf_log, name='api_sys_perf_log'),
    path('api_sys_perf_log_available_director', views.api_sys_perf_log_available_director, name='api_sys_perf_log_available_director'),
    path('api_sys_perf_log_columns', views.api_sys_perf_log_columns, name='api_sys_perf_log_columns'),
    path('api_vv_perf_log_columns', views.api_vv_perf_log_columns, name='api_vv_perf_log_columns'),
    path('api_sys_perf_log_timespan', views.api_sys_perf_log_timespan, name='api_sys_perf_log_timespan'),
    path('api_sys_perf_log_timestamps', views.api_sys_perf_log_timestamps, name='api_sys_perf_log_timestamps'),
    path('api_vv_perf_log_available_volumes', views.api_vv_perf_log_available_volumes, name='api_vv_perf_log_available_volumes'),
    path('api_sys_perf_log_by_columns', views.api_sys_perf_log_by_columns, name='api_sys_perf_log_by_columns'),
    path('api_cdlog_extraction_job', views.api_cdlog_extraction_job, name='api_cdlog_extraction_job'),
	path('api_hostname', views.api_hostname, name='api_hostname'),
    path('base_template', views.base_template, name='base_template'),
]