# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
# This role binding allows "sidecar" to read pods in the "development" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods-sidecar
  namespace: development
subjects:
- kind: ServiceAccount
  name: sidecar # Name is case sensitive
  namespace: development
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
