# Generated by Django 2.0.1 on 2018-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_id', models.IntegerField()),
                ('sr_oracle_id', models.IntegerField(null=True)),
                ('owner', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
