# Generated by Django 2.0.1 on 2018-01-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0002_auto_20180128_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(default='N/A', max_length=50)),
                ('component', models.CharField(default='N/A', max_length=50)),
                ('code', models.IntegerField(default=-1)),
                ('internalRCA', models.CharField(default='N/A', max_length=3000)),
                ('customerRCA', models.CharField(default='N/A', max_length=3000)),
                ('customerDescription', models.CharField(default='N/A', max_length=3000)),
                ('formatString', models.CharField(default='N/A', max_length=3000)),
            ],
        ),
    ]
