# Generated by Django 2.0.1 on 2018-01-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0004_investigation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlog',
            name='downloaded_succeed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdlog',
            name='local_directory',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='cdlog',
            name='remote_directory',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
