# Generated by Django 2.0.1 on 2018-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0005_auto_20180131_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdlog',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
