# Generated by Django 2.0.1 on 2018-02-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0007_auto_20180131_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlog',
            name='dump_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdlog',
            name='dump_succeed',
            field=models.BooleanField(default=False),
        ),
    ]
