# Generated by Django 2.0.1 on 2018-02-05 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0011_firmwarelog_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareLogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firmware_id', models.IntegerField()),
                ('text', models.CharField(max_length=5000)),
                ('ip', models.CharField(default='N/A', max_length=100)),
                ('director', models.CharField(default='N/A', max_length=50)),
                ('year', models.IntegerField(default=-1)),
                ('month', models.IntegerField(default=-1)),
                ('day', models.IntegerField(default=-1)),
                ('hour', models.IntegerField(default=-1)),
                ('minute', models.IntegerField(default=-1)),
                ('second', models.IntegerField(default=-1)),
                ('date_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('component', models.CharField(default='N/A', max_length=30)),
                ('event_id', models.IntegerField(default=-1)),
                ('i_port_name', models.CharField(default='N/A', max_length=100)),
                ('i_port', models.CharField(default='N/A', max_length=100)),
                ('t_port_name', models.CharField(default='N/A', max_length=100)),
                ('t_port', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='component',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='day',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='director',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='i_port',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='i_port_name',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='month',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='second',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='t_port',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='t_port_name',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='text',
        ),
        migrations.RemoveField(
            model_name='firmwarelog',
            name='year',
        ),
    ]
