# Generated by Django 2.0.1 on 2018-02-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0012_auto_20180205_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmwarelogentry',
            old_name='firmware_id',
            new_name='firmwarelog_id',
        ),
    ]
