# Generated by Django 2.0.2 on 2018-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0015_storage_view_view_initiator_view_initiator_target_login_view_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cdlog_id', models.IntegerField()),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('serial_number', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='director',
            old_name='cdlog_id',
            new_name='cluster_id',
        ),
        migrations.AddField(
            model_name='director',
            name='ip',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='uid',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
