# Generated by Django 2.0.2 on 2018-02-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0018_auto_20180218_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlog',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
