# Generated by Django 2.0.2 on 2018-02-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0020_auto_20180219_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage_view',
            old_name='staus',
            new_name='status',
        ),
    ]
