# Generated by Django 2.0.2 on 2018-02-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0021_auto_20180220_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_initiator',
            name='view_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='view_port',
            name='view_id',
            field=models.IntegerField(default=-1),
        ),
    ]
