# Generated by Django 2.0.2 on 2018-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0024_storage_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='storage_array_connectivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_array_id', models.IntegerField(default=-1)),
                ('i', models.CharField(default='N/A', max_length=150)),
                ('t', models.CharField(default='N/A', max_length=150)),
            ],
        ),
    ]
