# Generated by Django 2.0.2 on 2018-04-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0026_firmwarelog_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysPerfLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('director_id', models.IntegerField(default=-1)),
                ('log_segment_id', models.IntegerField(default=-1)),
                ('path', models.CharField(default='N/A', max_length=600)),
            ],
        ),
    ]
