# Generated by Django 2.0.4 on 2018-05-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0027_sysperflog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDLog_Extraction_Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cdlog_file', models.CharField(default='N/A', max_length=1000)),
                ('extracted_folder', models.CharField(default='N/A', max_length=1000)),
                ('state', models.CharField(default='NOT_STARTED', max_length=100)),
            ],
        ),
    ]
