# Generated by Django 2.0.4 on 2018-05-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0028_cdlog_extraction_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlog_extraction_job',
            name='cdlog_id',
            field=models.IntegerField(default=-1),
        ),
    ]
