# Generated by Django 2.0.4 on 2018-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0029_cdlog_extraction_job_cdlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlog_extraction_job',
            name='exception',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cdlog_extraction_job',
            name='returncode',
            field=models.IntegerField(default=0),
        ),
    ]
