# Generated by Django 2.0.4 on 2018-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0030_auto_20180508_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlog_extraction_job',
            name='owner',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
