# Generated by Django 2.0.5 on 2018-07-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vplex', '0031_cdlog_extraction_job_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVPerfLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('director_id', models.IntegerField(default=-1)),
                ('log_segment_id', models.IntegerField(default=-1)),
                ('path', models.CharField(default='N/A', max_length=600)),
            ],
        ),
    ]
